---
title: "DGE and GSEA example protocol"
author: "Marta Micek"
date: "2025-12-06"
output: pdf_document
---

```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(data.table)
#library(rtracklayer)
library(dplyr)
library(airway)
library(GenomeInfoDb)
library(DESeq2)
```

# Intro

A minimal protocol for DGE and GSEA analysis using raw counts as input. 

CTRL+ALT+I to create a new chunk.
CTRL+ENTER runs a line.

```{r}
data <- data("airway")
airway
assay(airway)[1:5, 1:5] # display counts
colData(airway)
rowData(airway)[1:5,]
```

# DESeq2

colData() shows a column called 'dex' that contains treatment information. It's the experiment design. There are also plenty of different approaches regarding filtering genes with overall low signal/expression.

```{r}
dds <- DESeqDataSet(
  airway,
  design = ~ dex
)

dds <- dds[rowSums(counts(dds)) >= 10, ] # remove genes with low signal
dds <- DESeq(dds)

res <- results(dds, contrast = c("dex", "trt", "untrt"))
resOrdered <- res[order(res$pvalue), ]
head(resOrdered)
```

